language: android

sudo: required
dist: trusty

env:
  global:
    # Try reducing initial heap size. https://discuss.gradle.org/t/gradle-travis-ci/11928
    - GRADLE_OPTS="-Xms128m"

jdk:
 - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

script:
  - ./gradlew build -s -i

after_success:
  - ./gradlew jacocoDebugReport coveralls

notifications:
  slack:
    rooms:
      - secure: N4ZZSQeKQSXgWDDuWMYzCb5+XLRf0inX5u8MqMJzoqbgYFgUhadlIvnSNofgIr715Rp/3ZlkkB5qPoOC27PD5TQNa44n+lfSvt1xENuduEv5ogXzqItPfoEcxyf2J5g3bv+UuuERv3nHwkhcpwJYASDKDj+jpubNS4RpYwqEkprva5j9titJW3ODye9q5YSo2kiSXvR/OkEf2KyEYlYlZqABsFm2lDyUhJ9S05A+9izZ7NyQZlynJRZI2hj7PrUwCt7mC0RIqaYySNgInAjapIVyKRpATffV6A5OtcK8kjjUs1Lg79MsEOjyvxZkBDbbm/qQO4smPKgezInSUfhEyEi7zpKThmzklWVSSCnlNgPgX/J68dgYx+/xUeJS4O25JBpmwPsbPN6xwmvrYgX19bvmX97iaEsr2tukyOQ7Nr8iIleXlBp9vPmbiUK4Zhk7kr2wEjxrBrQwW4eiiYU4R7BEeZr9SMOYL0ViDQDoxUMsnY2nh7H3V8EiZxGKdDsryCRjP5LwykcIhRlpO/dl7peAwl3iOWaKId0laW0PAciZIAORxEEHWc+a9Z8kBBJ/BNpxa5vuWBA/hhfgnsxRN8ymK1JjIZm/AQreWOuScW8ettDcSuJAkafyIhffni3OgNuJOeq71+K/KrjWIjrmtWA+ognwaA/2lH8LrBzN7cg=
      - permission-nanny:ZgNsHtoW3DcEvUmWtAFmIu1l#bot-travis
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ae15e0fa42aba8e0e04
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
